collect_csm_documents:
  description: >
    Conduct a thorough research about the CSM information for client {client}.
    Make sure you find any interesting and relevant information about the CSMs.
    You can use the following data sources:
    - ADV form
    - cRDS
    - other internal data sources
    - other public data sources
    - other sources you can find on the internet
  expected_output: >
    A list of CSMs for client {client} with the following information:
    - Name
    - Email
    - Phone
    - Title
    - Department
    - Company
    - origin of the CSM information, such as name of the document with page number, or the source of the information
  agent: csm_researcher

report_csm_list:
  description: >
    Review the documents collected by the CSM researcher and create a list of CSMs for client {client}.
    Make sure the list is complete and contains any and all relevant information.

    Please incorporate the following feedback if present: 
    {feedback}
  expected_output: >
    A list of CSMs for client {client} with the following information:
    - Name
    - Email
    - Phone
    - Title
    - Department
    - Company
    - origin of the CSM information, such as name of the document with page number, or the source of the information
  agent: csm_reporting_analyst  
